export const AuditActions = {
  USER_LOGIN: 'USER_LOGIN',
  USER_CREATED: 'USER_CREATED',
  USER_PASSWORD_CHANGED: 'USER_PASSWORD_CHANGED',
  APPOINTMENT_CREATED: 'APPOINTMENT_CREATED',
  TREATMENT_APPROVED: 'TREATMENT_APPROVED',
  DOCTOR_STATUS_CHANGED: 'DOCTOR_STATUS_CHANGED',
  PATIENT_CREATED: 'PATIENT_CREATED',
  PATIENT_UPDATED: 'PATIENT_UPDATED',
  PATIENT_STATUS_CHANGED: 'PATIENT_STATUS_CHANGED',
};