export const AuditActions = {
  USER_LOGIN: 'USER_LOGIN',
  USER_CREATED: 'USER_CREATED',
  APPOINTMENT_CREATED: 'APPOINTMENT_CREATED',
  TREATMENT_APPROVED: 'TREATMENT_APPROVED',
  DOCTOR_STATUS_CHANGED: 'DOCTOR_STATUS_CHANGED',
};